openapi: 3.0.0
info:
    title: Leave Balance
    version: 1.0.0
    description: APIs for Leave Balance
paths:
    /getLeaveBalance/{empID}:
        get:
            summary: Retrieve the leave balance for an employee
            description: Retrieve the leave balance for an employee by providing the employee ID
            operationId: getLeaveBalance
            parameters:
                - name: empID
                  in: path
                  description: Unique ID of the leave balance for an employee
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Return Leave Balance of the employees
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    leaveBalance:
                                        type: string
                                        description: Employee's leave balance number remaining
                                    employeeName:
                                        type: string
                                        description: Employee Name
                "400":
                    description: Bad request. One or more required fields are missing or invalid.
